### Get customer Service
GET http://localhost:8091/customer-service/default

### Get Product Service
GET http://root:s3cr3t@localhost:8091/service-product/default


### Get customer Service
GET http://root:s3cr3t@localhost:8090/customer-service/default


### Get customer Service with config server
GET http://localhost:8091/customers

### Get product Service with config server
GET http://localhost:8092/products/1

### Get invoice Service with config server
POST http://localhost:8093/invoices HTTP/1.1
content-type: application/json

{
    "numberInvoice": "002",
    "description": "invoice store",
    "customerId": 1,
    "items": [
        {
            "quantity": 1,
            "priceItem": 178.89,
            "productId": 1
        },

        {
            "quantity": 2,
            "priceItem": 40.06,
            "productId": 3
        }
    ]
}

### Get product Service with config server
GET http://localhost:8093/invoices/1
