### Get
GET http://localhost:8091/customers


### post
POST http://localhost:8091/customers HTTP/1.1
content-type: application/json

{
    "numberID":"40408083",
    "firstName": "Luis",
    "lastName": "rodriguez",
    "email": "profesor@digitallab.academy",
    "photoUrl": "",
    "region": {
        "id": 1
    }
}



